blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: <TOOL REPO>/discussions/new?category=ideas
    about: Feature requests should be opened as discussions
  - name: Ask a question
    url: <TOOL REPO>/discussions/new?category=help
    about: Ask questions and discuss with other community members
